version: "3.8"

services:
  server:
    build: ./server
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/server

  #client
  node:
    image: "node:18-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./client/:/home/node/app
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=3000
    command: sh -c "yarn install && yarn run start"
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./db:/var/lib/mysql
