version: "3.8"

services:
  server:
    build: ./server
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/server

  client:
    build: ./client/
    links:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/code
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./db:/var/lib/mysql
