version: "3.8"

services:
  server:
    build: ./server
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/server

  # client:
  #   image: ./client
  #   links:
  #     - server
  #   ports:
  #     - "3006:3006"
  #   volumes:
  #     - "./client:/client"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
